name: Deploy GitHub pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v7
      - name: Prepare build environment
        run: |
          mkdir -p build
          touch build/.nojekyll
      - name: Run pandoc
        uses: docker://pandoc/core:3.10
        with:
          args: >-
            --standalone
            --output=build/index.html
            README.md
      - name: Deploy on github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
